version: '3.8'

services:
  # Service Mason (dépendance pour les autres services)
  mason:
    build:
      context: .
      dockerfile: docker/mason/Dockerfile
      ssh:
        - default
      args:
        - MASON_REPO_URL=${MASON_REPO_URL:-git@bitbucket.org:pcafxc/mason.git}
        - MASON_BRANCH=${MASON_BRANCH:-feature/RETRIEVER-511}
    volumes:
      - maven_cache:/root/.m2
    networks:
      - cardmanager-network

  # Service Painter (traitement d'images)
  painter:
    build:
      context: .
      dockerfile: docker/painter/Dockerfile
      ssh:
        - default
      args:
        - MASON_REPO_URL=${MASON_REPO_URL:-git@bitbucket.org:pcafxc/mason.git}
        - MASON_BRANCH=${MASON_BRANCH:-feature/RETRIEVER-511}
        - PAINTER_REPO_URL=${PAINTER_REPO_URL:-git@bitbucket.org:pcafxc/painter.git}
        - PAINTER_BRANCH=${PAINTER_BRANCH:-feature/card-manager-511}
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PAINTER_IMAGE_STORAGE_PATH=/app/images
      - DATABASE_URL=jdbc:mariadb://mariadb-standalone:3306/dev
      - DATABASE_USERNAME=ia
      - DATABASE_PASSWORD=foufafou
    volumes:
      - cardmanager_images:/app/images
      - maven_cache:/root/.m2
    depends_on:
      - mariadb-standalone
      - mason
    networks:
      - cardmanager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Service GestionCarte (application principale)
  gestioncarte:
    build:
      context: .
      dockerfile: docker/gestioncarte/Dockerfile
      ssh:
        - default
      args:
        - MASON_REPO_URL=${MASON_REPO_URL:-git@bitbucket.org:pcafxc/mason.git}
        - MASON_BRANCH=${MASON_BRANCH:-feature/RETRIEVER-511}
        - PAINTER_REPO_URL=${PAINTER_REPO_URL:-git@bitbucket.org:pcafxc/painter.git}
        - PAINTER_BRANCH=${PAINTER_BRANCH:-feature/card-manager-511}
        - GESTIONCARTE_REPO_URL=${GESTIONCARTE_REPO_URL:-git@bitbucket.org:pcafxc/gestioncarte.git}
        - GESTIONCARTE_BRANCH=${GESTIONCARTE_BRANCH:-feature/card-manager-511}
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:mariadb://mariadb-standalone:3306/dev
      - DATABASE_USERNAME=ia
      - DATABASE_PASSWORD=foufafou
      - PAINTER_SERVICE_URL=http://painter:8081
    volumes:
      - maven_cache:/root/.m2
    depends_on:
      - mariadb-standalone
      - painter
      - mason
    networks:
      - cardmanager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  # Base de données MariaDB
  mariadb-standalone:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=dev
      - MYSQL_USER=ia
      - MYSQL_PASSWORD=foufafou
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - cardmanager_db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d:ro
    networks:
      - cardmanager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "ia", "-pfoufafou"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_connections=200
      --innodb_buffer_pool_size=256M

  # Serveur d'images Nginx
  nginx-images:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - cardmanager_images:/usr/share/nginx/html/images:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cardmanager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

# Volumes persistants
volumes:
  cardmanager_db_data:
    driver: local
  cardmanager_images:
    driver: local
  maven_cache:
    driver: local

# Réseau interne
networks:
  cardmanager-network:
    driver: bridge